# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1165, 807)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/ui/assert/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalGroupBox_main = QtWidgets.QGroupBox(self.centralwidget)
        self.verticalGroupBox_main.setMaximumSize(QtCore.QSize(1146, 16777215))
        self.verticalGroupBox_main.setStyleSheet("background-color: rgb(255, 253, 247);")
        self.verticalGroupBox_main.setObjectName("verticalGroupBox_main")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalGroupBox_main)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalGroupBox = QtWidgets.QGroupBox(self.verticalGroupBox_main)
        self.horizontalGroupBox.setMinimumSize(QtCore.QSize(0, 50))
        self.horizontalGroupBox.setMaximumSize(QtCore.QSize(1146, 50))
        self.horizontalGroupBox.setStyleSheet("#horizontalGroupBox{border: 1px solid;\n"
"    border-color: rgb(118, 118, 118);\n"
"}")
        self.horizontalGroupBox.setObjectName("horizontalGroupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalGroupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_item = QtWidgets.QLabel(self.horizontalGroupBox)
        self.label_item.setMinimumSize(QtCore.QSize(0, 0))
        self.label_item.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_item.setStyleSheet("    font: 11pt \"黑体\";\n"
"    font-size:23px;\n"
"    font-weight: bold;\n"
"         border-radius:9px;\n"
"        background:rgba(66, 195, 255, 0);\n"
"        color: rgb(118, 118, 118);\n"
"\n"
"")
        self.label_item.setObjectName("label_item")
        self.horizontalLayout.addWidget(self.label_item)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.horizontalGroupBox)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalGroupBox = QtWidgets.QGroupBox(self.verticalGroupBox_main)
        self.verticalGroupBox.setMaximumSize(QtCore.QSize(331, 16777215))
        self.verticalGroupBox.setStyleSheet("#verticalGroupBox{border: 1px solid;\n"
"border-color: rgb(118, 118, 118);}")
        self.verticalGroupBox.setObjectName("verticalGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalGroupBox1 = QtWidgets.QGroupBox(self.verticalGroupBox)
        self.verticalGroupBox1.setMinimumSize(QtCore.QSize(0, 0))
        self.verticalGroupBox1.setMaximumSize(QtCore.QSize(16777215, 45))
        self.verticalGroupBox1.setStyleSheet("#verticalGroupBox{border: 1px solid;\n"
"    \n"
"    border-color: rgba(118, 118, 118, 30);}")
        self.verticalGroupBox1.setObjectName("verticalGroupBox1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalGroupBox1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_load_query = QtWidgets.QLabel(self.verticalGroupBox1)
        self.label_load_query.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_load_query.setStyleSheet("    \n"
"font: 9pt \"黑体\";\n"
"    font-size:18px;\n"
"    font-weight: bold;\n"
"         border-radius:9px;\n"
"        background:rgba(66, 195, 255, 0);\n"
"        color: rgb(118, 118, 118);\n"
"")
        self.label_load_query.setObjectName("label_load_query")
        self.verticalLayout_4.addWidget(self.label_load_query)
        self.verticalLayout_2.addWidget(self.verticalGroupBox1)
        self.horizontalGroupBox1 = QtWidgets.QGroupBox(self.verticalGroupBox)
        self.horizontalGroupBox1.setMinimumSize(QtCore.QSize(0, 50))
        self.horizontalGroupBox1.setMaximumSize(QtCore.QSize(16777215, 55))
        self.horizontalGroupBox1.setStyleSheet("#horizontalGroupBox{border: 1px solid;\n"
"    border-color: rgb(118, 118, 118, 30);}")
        self.horizontalGroupBox1.setObjectName("horizontalGroupBox1")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalGroupBox1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_query = QtWidgets.QPushButton(self.horizontalGroupBox1)
        self.pushButton_query.setMinimumSize(QtCore.QSize(61, 30))
        self.pushButton_query.setStyleSheet("QPushButton{font-family: \"Microsoft YaHei\";\n"
"\n"
"background-color: rgb(118, 118, 118);\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"color:white;\n"
"text-align: center center;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"padding-top: 4px;\n"
"padding-bottom: 4px;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-color: rgba(255, 255, 255, 255);\n"
"border-radius: 3px;}\n"
"\n"
"QPushButton:focus{outline: none;}\n"
"\n"
"QPushButton::pressed{font-family: \"Microsoft YaHei\";\n"
"                     font-size: 14px;\n"
"                     font-weight: bold;\n"
"                     color:rgb(200,200,200);\n"
"                     text-align: center center;\n"
"                     padding-left: 5px;\n"
"                     padding-right: 5px;\n"
"                     padding-top: 4px;\n"
"                     padding-bottom: 4px;\n"
"                     border-style: solid;\n"
"                     border-width: 0px;\n"
"                     border-color: rgba(255, 255, 255, 255);\n"
"                     border-radius: 3px;\n"
"                     background-color:  #bf513b;}\n"
"\n"
"QPushButton::disabled{font-family: \"Microsoft YaHei\";\n"
"                     font-size: 14px;\n"
"                     font-weight: bold;\n"
"                     color:rgb(200,200,200);\n"
"                     text-align: center center;\n"
"                     padding-left: 5px;\n"
"                     padding-right: 5px;\n"
"                     padding-top: 4px;\n"
"                     padding-bottom: 4px;\n"
"                     border-style: solid;\n"
"                     border-width: 0px;\n"
"                     border-color: rgba(255, 255, 255, 255);\n"
"                     border-radius: 3px;\n"
"                     background-color:  #bf513b;}\n"
"QPushButton::hover {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(48,148,243,80);}")
        self.pushButton_query.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ui/assert/file_open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_query.setIcon(icon1)
        self.pushButton_query.setObjectName("pushButton_query")
        self.horizontalLayout_10.addWidget(self.pushButton_query)
        self.lineEdit_query = QtWidgets.QLineEdit(self.horizontalGroupBox1)
        self.lineEdit_query.setMaximumSize(QtCore.QSize(241, 30))
        self.lineEdit_query.setObjectName("lineEdit_query")
        self.horizontalLayout_10.addWidget(self.lineEdit_query)
        self.verticalLayout_2.addWidget(self.horizontalGroupBox1)
        self.verticalGroupBox_6 = QtWidgets.QGroupBox(self.verticalGroupBox)
        self.verticalGroupBox_6.setMaximumSize(QtCore.QSize(16777215, 45))
        self.verticalGroupBox_6.setStyleSheet("#verticalGroupBox_6{border: 1px solid;\n"
"    border-color: rgba(118, 118, 118, 30);}")
        self.verticalGroupBox_6.setObjectName("verticalGroupBox_6")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.verticalGroupBox_6)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_load_ref = QtWidgets.QLabel(self.verticalGroupBox_6)
        self.label_load_ref.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_load_ref.setAutoFillBackground(False)
        self.label_load_ref.setStyleSheet("    \n"
"font: 9pt \"黑体\";\n"
"    font-size:18px;\n"
"    font-weight: bold;\n"
"         border-radius:9px;\n"
"        background:rgba(66, 195, 255, 0);\n"
"        color: rgb(118, 118, 118);\n"
"")
        self.label_load_ref.setObjectName("label_load_ref")
        self.verticalLayout_12.addWidget(self.label_load_ref)
        self.verticalLayout_2.addWidget(self.verticalGroupBox_6)
        self.horizontalGroupBox2 = QtWidgets.QGroupBox(self.verticalGroupBox)
        self.horizontalGroupBox2.setMinimumSize(QtCore.QSize(0, 50))
        self.horizontalGroupBox2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.horizontalGroupBox2.setStyleSheet("#horizontalGroupBox{border: 1px solid;\n"
"    border-color: rgba(118, 118, 118, 30);}")
        self.horizontalGroupBox2.setObjectName("horizontalGroupBox2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalGroupBox2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_ref = QtWidgets.QPushButton(self.horizontalGroupBox2)
        self.pushButton_ref.setMinimumSize(QtCore.QSize(61, 30))
        self.pushButton_ref.setStyleSheet("QPushButton{font-family: \"Microsoft YaHei\";\n"
"\n"
"background-color: rgb(118, 118, 118);\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"color:white;\n"
"text-align: center center;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"padding-top: 4px;\n"
"padding-bottom: 4px;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-color: rgba(255, 255, 255, 255);\n"
"border-radius: 3px;}\n"
"\n"
"QPushButton:focus{outline: none;}\n"
"\n"
"QPushButton::pressed{font-family: \"Microsoft YaHei\";\n"
"                     font-size: 14px;\n"
"                     font-weight: bold;\n"
"                     color:rgb(200,200,200);\n"
"                     text-align: center center;\n"
"                     padding-left: 5px;\n"
"                     padding-right: 5px;\n"
"                     padding-top: 4px;\n"
"                     padding-bottom: 4px;\n"
"                     border-style: solid;\n"
"                     border-width: 0px;\n"
"                     border-color: rgba(255, 255, 255, 255);\n"
"                     border-radius: 3px;\n"
"                     background-color:  #bf513b;}\n"
"\n"
"QPushButton::disabled{font-family: \"Microsoft YaHei\";\n"
"                     font-size: 14px;\n"
"                     font-weight: bold;\n"
"                     color:rgb(200,200,200);\n"
"                     text-align: center center;\n"
"                     padding-left: 5px;\n"
"                     padding-right: 5px;\n"
"                     padding-top: 4px;\n"
"                     padding-bottom: 4px;\n"
"                     border-style: solid;\n"
"                     border-width: 0px;\n"
"                     border-color: rgba(255, 255, 255, 255);\n"
"                     border-radius: 3px;\n"
"                     background-color:  #bf513b;}\n"
"QPushButton::hover {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(48,148,243,80);}")
        self.pushButton_ref.setText("")
        self.pushButton_ref.setIcon(icon1)
        self.pushButton_ref.setObjectName("pushButton_ref")
        self.horizontalLayout_9.addWidget(self.pushButton_ref)
        self.lineEdit_ref = QtWidgets.QLineEdit(self.horizontalGroupBox2)
        self.lineEdit_ref.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_ref.setMaximumSize(QtCore.QSize(241, 30))
        self.lineEdit_ref.setObjectName("lineEdit_ref")
        self.horizontalLayout_9.addWidget(self.lineEdit_ref)
        self.verticalLayout_2.addWidget(self.horizontalGroupBox2)
        self.verticalGroupBox_4 = QtWidgets.QGroupBox(self.verticalGroupBox)
        self.verticalGroupBox_4.setMaximumSize(QtCore.QSize(16777215, 45))
        self.verticalGroupBox_4.setStyleSheet("#verticalGroupBox_4{border: 1px solid;\n"
"    border-color: rgba(118, 118, 118, 30);}")
        self.verticalGroupBox_4.setObjectName("verticalGroupBox_4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalGroupBox_4)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_load_open = QtWidgets.QLabel(self.verticalGroupBox_4)
        self.label_load_open.setEnabled(True)
        self.label_load_open.setMinimumSize(QtCore.QSize(0, 0))
        self.label_load_open.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_load_open.setStyleSheet("    \n"
"font: 9pt \"黑体\";\n"
"    font-size:18px;\n"
"    font-weight: bold;\n"
"         border-radius:9px;\n"
"        background:rgba(66, 195, 255, 0);\n"
"        color: rgb(118, 118, 118);\n"
"")
        self.label_load_open.setObjectName("label_load_open")
        self.verticalLayout_10.addWidget(self.label_load_open)
        self.verticalLayout_2.addWidget(self.verticalGroupBox_4)
        self.horizontalGroupBox3 = QtWidgets.QGroupBox(self.verticalGroupBox)
        self.horizontalGroupBox3.setMinimumSize(QtCore.QSize(0, 50))
        self.horizontalGroupBox3.setStyleSheet("#horizontalGroupBox{border: 1px solid;\n"
"    border-color: rgba(118, 118, 118, 30);}")
        self.horizontalGroupBox3.setObjectName("horizontalGroupBox3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalGroupBox3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_open = QtWidgets.QPushButton(self.horizontalGroupBox3)
        self.pushButton_open.setMinimumSize(QtCore.QSize(61, 30))
        self.pushButton_open.setStyleSheet("QPushButton{font-family: \"Microsoft YaHei\";\n"
"\n"
"background-color: rgb(118, 118, 118);\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"color:white;\n"
"text-align: center center;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"padding-top: 4px;\n"
"padding-bottom: 4px;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-color: rgba(255, 255, 255, 255);\n"
"border-radius: 3px;}\n"
"\n"
"QPushButton:focus{outline: none;}\n"
"\n"
"QPushButton::pressed{font-family: \"Microsoft YaHei\";\n"
"                     font-size: 14px;\n"
"                     font-weight: bold;\n"
"                     color:rgb(200,200,200);\n"
"                     text-align: center center;\n"
"                     padding-left: 5px;\n"
"                     padding-right: 5px;\n"
"                     padding-top: 4px;\n"
"                     padding-bottom: 4px;\n"
"                     border-style: solid;\n"
"                     border-width: 0px;\n"
"                     border-color: rgba(255, 255, 255, 255);\n"
"                     border-radius: 3px;\n"
"                     background-color:  #bf513b;}\n"
"\n"
"QPushButton::disabled{font-family: \"Microsoft YaHei\";\n"
"                     font-size: 14px;\n"
"                     font-weight: bold;\n"
"                     color:rgb(200,200,200);\n"
"                     text-align: center center;\n"
"                     padding-left: 5px;\n"
"                     padding-right: 5px;\n"
"                     padding-top: 4px;\n"
"                     padding-bottom: 4px;\n"
"                     border-style: solid;\n"
"                     border-width: 0px;\n"
"                     border-color: rgba(255, 255, 255, 255);\n"
"                     border-radius: 3px;\n"
"                     background-color:  #bf513b;}\n"
"QPushButton::hover {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(48,148,243,80);}")
        self.pushButton_open.setText("")
        self.pushButton_open.setIcon(icon1)
        self.pushButton_open.setObjectName("pushButton_open")
        self.horizontalLayout_7.addWidget(self.pushButton_open)
        self.lineEdit_open = QtWidgets.QLineEdit(self.horizontalGroupBox3)
        self.lineEdit_open.setMaximumSize(QtCore.QSize(241, 31))
        self.lineEdit_open.setObjectName("lineEdit_open")
        self.horizontalLayout_7.addWidget(self.lineEdit_open)
        self.verticalLayout_2.addWidget(self.horizontalGroupBox3)
        self.horizontalGroupBox_2 = QtWidgets.QGroupBox(self.verticalGroupBox)
        self.horizontalGroupBox_2.setMinimumSize(QtCore.QSize(0, 210))
        self.horizontalGroupBox_2.setMaximumSize(QtCore.QSize(16777215, 210))
        self.horizontalGroupBox_2.setStyleSheet("#horizontalGroupBox_2{border: 0px solid;}")
        self.horizontalGroupBox_2.setObjectName("horizontalGroupBox_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalGroupBox_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.label_img_query = QtWidgets.QLabel(self.horizontalGroupBox_2)
        self.label_img_query.setMinimumSize(QtCore.QSize(130, 0))
        self.label_img_query.setMaximumSize(QtCore.QSize(16777215, 190))
        self.label_img_query.setText("")
        self.label_img_query.setObjectName("label_img_query")
        self.horizontalLayout_5.addWidget(self.label_img_query)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout_2.addWidget(self.horizontalGroupBox_2)
        self.verticalGroupBox_3 = QtWidgets.QGroupBox(self.verticalGroupBox)
        self.verticalGroupBox_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.verticalGroupBox_3.setStyleSheet("#verticalGroupBox_3{border: 1px solid;\n"
"    border-color: rgba(118, 118, 118, 30);}")
        self.verticalGroupBox_3.setObjectName("verticalGroupBox_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalGroupBox_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_load_assessment = QtWidgets.QLabel(self.verticalGroupBox_3)
        self.label_load_assessment.setMaximumSize(QtCore.QSize(16777215, 45))
        self.label_load_assessment.setStyleSheet("    \n"
"font: 9pt \"黑体\";\n"
"    font-size:18px;\n"
"    font-weight: bold;\n"
"         border-radius:9px;\n"
"        background:rgba(66, 195, 255, 0);\n"
"        color: rgb(118, 118, 118);\n"
"")
        self.label_load_assessment.setObjectName("label_load_assessment")
        self.verticalLayout_8.addWidget(self.label_load_assessment)
        self.verticalLayout_2.addWidget(self.verticalGroupBox_3)
        self.verticalGroupBox_8 = QtWidgets.QGroupBox(self.verticalGroupBox)
        self.verticalGroupBox_8.setMaximumSize(QtCore.QSize(16777215, 160))
        self.verticalGroupBox_8.setStyleSheet("#verticalGroupBox_8{border: 0px solid;}")
        self.verticalGroupBox_8.setObjectName("verticalGroupBox_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalGroupBox_8)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.verticalGroupBox_8)
        self.plainTextEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_5.addWidget(self.plainTextEdit)
        self.verticalLayout_2.addWidget(self.verticalGroupBox_8)
        self.verticalGroupBox_8.raise_()
        self.verticalGroupBox.raise_()
        self.verticalGroupBox_3.raise_()
        self.verticalGroupBox_4.raise_()
        self.verticalGroupBox_6.raise_()
        self.horizontalGroupBox_2.raise_()
        self.horizontalGroupBox.raise_()
        self.horizontalGroupBox.raise_()
        self.horizontalGroupBox.raise_()
        self.horizontalLayout_11.addWidget(self.verticalGroupBox)
        self.verticalGroupBox_output = QtWidgets.QGroupBox(self.verticalGroupBox_main)
        self.verticalGroupBox_output.setStyleSheet("#verticalGroupBox_output{border: 1px solid;\n"
"    border-color: rgb(118, 118, 118);}")
        self.verticalGroupBox_output.setObjectName("verticalGroupBox_output")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalGroupBox_output)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalGroupBox_3 = QtWidgets.QGroupBox(self.verticalGroupBox_output)
        self.horizontalGroupBox_3.setMinimumSize(QtCore.QSize(0, 57))
        self.horizontalGroupBox_3.setStyleSheet("#horizontalGroupBox_3{border: 0px solid;}")
        self.horizontalGroupBox_3.setObjectName("horizontalGroupBox_3")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.horizontalGroupBox_3)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButton_start = QtWidgets.QPushButton(self.horizontalGroupBox_3)
        self.pushButton_start.setMinimumSize(QtCore.QSize(100, 45))
        self.pushButton_start.setStyleSheet("QPushButton{font-family: \"Microsoft YaHei\";\n"
"\n"
"background-color: rgb(118, 118, 118);\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"color:white;\n"
"text-align: center center;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"padding-top: 4px;\n"
"padding-bottom: 4px;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-color: rgba(255, 255, 255, 255);\n"
"border-radius: 3px;}\n"
"\n"
"QPushButton:focus{outline: none;}\n"
"\n"
"QPushButton::pressed{font-family: \"Microsoft YaHei\";\n"
"                     font-size: 14px;\n"
"                     font-weight: bold;\n"
"                     color:rgb(200,200,200);\n"
"                     text-align: center center;\n"
"                     padding-left: 5px;\n"
"                     padding-right: 5px;\n"
"                     padding-top: 4px;\n"
"                     padding-bottom: 4px;\n"
"                     border-style: solid;\n"
"                     border-width: 0px;\n"
"                     border-color: rgba(255, 255, 255, 255);\n"
"                     border-radius: 3px;\n"
"                     background-color:  #bf513b;}\n"
"\n"
"QPushButton::disabled{font-family: \"Microsoft YaHei\";\n"
"                     font-size: 14px;\n"
"                     font-weight: bold;\n"
"                     color:rgb(200,200,200);\n"
"                     text-align: center center;\n"
"                     padding-left: 5px;\n"
"                     padding-right: 5px;\n"
"                     padding-top: 4px;\n"
"                     padding-bottom: 4px;\n"
"                     border-style: solid;\n"
"                     border-width: 0px;\n"
"                     border-color: rgba(255, 255, 255, 255);\n"
"                     border-radius: 3px;\n"
"                     background-color:  #bf513b;}\n"
"QPushButton::hover {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(48,148,243,80);}")
        self.pushButton_start.setObjectName("pushButton_start")
        self.horizontalLayout_12.addWidget(self.pushButton_start)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.pushButton_cancel = QtWidgets.QPushButton(self.horizontalGroupBox_3)
        self.pushButton_cancel.setMinimumSize(QtCore.QSize(100, 45))
        self.pushButton_cancel.setStyleSheet("QPushButton{font-family: \"Microsoft YaHei\";\n"
"\n"
"background-color: rgb(118, 118, 118);\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"color:white;\n"
"text-align: center center;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"padding-top: 4px;\n"
"padding-bottom: 4px;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-color: rgba(255, 255, 255, 255);\n"
"border-radius: 3px;}\n"
"\n"
"QPushButton:focus{outline: none;}\n"
"\n"
"QPushButton::pressed{font-family: \"Microsoft YaHei\";\n"
"                     font-size: 14px;\n"
"                     font-weight: bold;\n"
"                     color:rgb(200,200,200);\n"
"                     text-align: center center;\n"
"                     padding-left: 5px;\n"
"                     padding-right: 5px;\n"
"                     padding-top: 4px;\n"
"                     padding-bottom: 4px;\n"
"                     border-style: solid;\n"
"                     border-width: 0px;\n"
"                     border-color: rgba(255, 255, 255, 255);\n"
"                     border-radius: 3px;\n"
"                     background-color:  #bf513b;}\n"
"\n"
"QPushButton::disabled{font-family: \"Microsoft YaHei\";\n"
"                     font-size: 14px;\n"
"                     font-weight: bold;\n"
"                     color:rgb(200,200,200);\n"
"                     text-align: center center;\n"
"                     padding-left: 5px;\n"
"                     padding-right: 5px;\n"
"                     padding-top: 4px;\n"
"                     padding-bottom: 4px;\n"
"                     border-style: solid;\n"
"                     border-width: 0px;\n"
"                     border-color: rgba(255, 255, 255, 255);\n"
"                     border-radius: 3px;\n"
"                     background-color:  #bf513b;}\n"
"QPushButton::hover {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(48,148,243,80);}")
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout_12.addWidget(self.pushButton_cancel)
        self.verticalLayout_3.addWidget(self.horizontalGroupBox_3)
        self.verticalGroupBox_2 = QtWidgets.QGroupBox(self.verticalGroupBox_output)
        self.verticalGroupBox_2.setStyleSheet("#verticalGroupBox_2{border: 1px solid;\n"
"    border-color: rgba(118, 118, 118, 30);}")
        self.verticalGroupBox_2.setObjectName("verticalGroupBox_2")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.verticalGroupBox_2)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_11 = QtWidgets.QLabel(self.verticalGroupBox_2)
        self.label_11.setMinimumSize(QtCore.QSize(91, 140))
        self.label_11.setStyleSheet("border-width: 2px;\n"
"background-color: rgba(118, 118, 118, 0);\n"
"border-style: solid;\n"
"border-color: rgb(118, 118, 118);\n"
"")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 5, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.verticalGroupBox_2)
        self.label_4.setMinimumSize(QtCore.QSize(91, 140))
        self.label_4.setStyleSheet("border-width: 2px;\n"
"background-color: rgba(118, 118, 118, 0);\n"
"border-style: solid;\n"
"border-color: rgb(118, 118, 118);\n"
"")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 7, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 1, 4, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 3, 6, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 1, 6, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.verticalGroupBox_2)
        self.label_8.setStyleSheet("border-width: 2px;\n"
"background-color: rgba(118, 118, 118, 0);\n"
"border-style: solid;\n"
"border-color: rgb(118, 118, 118);\n"
"")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 5, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 3, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.verticalGroupBox_2)
        self.label_12.setStyleSheet("border-width: 2px;\n"
"background-color: rgba(118, 118, 118, 0);\n"
"border-style: solid;\n"
"border-color: rgb(118, 118, 118);\n"
"")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 5, 3, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 3, 4, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem10, 7, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem11, 7, 6, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem12, 1, 8, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem13, 7, 2, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem14, 5, 4, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem15, 5, 6, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem16, 5, 8, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.verticalGroupBox_2)
        self.label_7.setStyleSheet("border-width: 2px;\n"
"background-color: rgba(118, 118, 118, 0);\n"
"border-style: solid;\n"
"border-color: rgb(118, 118, 118);\n"
"")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 3, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem17, 5, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.verticalGroupBox_2)
        self.label_3.setMinimumSize(QtCore.QSize(91, 140))
        self.label_3.setStyleSheet("border-width: 2px;\n"
"background-color: rgba(118, 118, 118, 0);\n"
"border-style: solid;\n"
"border-color: rgb(118, 118, 118);\n"
"")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 5, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem18, 1, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.verticalGroupBox_2)
        self.label_13.setStyleSheet("border-width: 2px;\n"
"background-color: rgba(118, 118, 118, 0);\n"
"border-style: solid;\n"
"border-color: rgb(118, 118, 118);\n"
"")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 5, 5, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem19, 3, 8, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.verticalGroupBox_2)
        self.label_16.setMinimumSize(QtCore.QSize(91, 140))
        self.label_16.setStyleSheet("border-width: 2px;\n"
"background-color: rgba(118, 118, 118, 0);\n"
"border-style: solid;\n"
"border-color: rgb(118, 118, 118);\n"
"")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 7, 1, 1, 1)
        self.label_1 = QtWidgets.QLabel(self.verticalGroupBox_2)
        self.label_1.setMinimumSize(QtCore.QSize(91, 140))
        self.label_1.setStyleSheet("border-width: 2px;\n"
"background-color: rgba(118, 118, 118, 0);\n"
"border-style: solid;\n"
"border-color: rgb(118, 118, 118);\n"
"")
        self.label_1.setText("")
        self.label_1.setObjectName("label_1")
        self.gridLayout.addWidget(self.label_1, 1, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.verticalGroupBox_2)
        self.label_20.setStyleSheet("border-width: 2px;\n"
"background-color: rgba(118, 118, 118, 0);\n"
"border-style: solid;\n"
"border-color: rgb(118, 118, 118);\n"
"")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 7, 9, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem20, 5, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.verticalGroupBox_2)
        self.label_5.setMinimumSize(QtCore.QSize(91, 140))
        self.label_5.setStyleSheet("border-width: 2px;\n"
"background-color: rgba(118, 118, 118, 0);\n"
"border-style: solid;\n"
"border-color: rgb(118, 118, 118);\n"
"")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 9, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.verticalGroupBox_2)
        self.label_2.setMinimumSize(QtCore.QSize(91, 140))
        self.label_2.setStyleSheet("border-width: 2px;\n"
"background-color: rgba(118, 118, 118, 0);\n"
"border-style: solid;\n"
"border-color: rgb(118, 118, 118);\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 3, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.verticalGroupBox_2)
        self.label_19.setStyleSheet("border-width: 2px;\n"
"background-color: rgba(118, 118, 118, 0);\n"
"border-style: solid;\n"
"border-color: rgb(118, 118, 118);\n"
"")
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 7, 7, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.verticalGroupBox_2)
        self.label_18.setStyleSheet("border-width: 2px;\n"
"background-color: rgba(118, 118, 118, 0);\n"
"border-style: solid;\n"
"border-color: rgb(118, 118, 118);\n"
"")
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 7, 5, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.verticalGroupBox_2)
        self.label_15.setStyleSheet("border-width: 2px;\n"
"background-color: rgba(118, 118, 118, 0);\n"
"border-style: solid;\n"
"border-color: rgb(118, 118, 118);\n"
"")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 5, 9, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem21, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.verticalGroupBox_2)
        self.label_14.setStyleSheet("border-width: 2px;\n"
"background-color: rgba(118, 118, 118, 0);\n"
"border-style: solid;\n"
"border-color: rgb(118, 118, 118);\n"
"")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 5, 7, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem22, 5, 10, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.verticalGroupBox_2)
        self.label_9.setStyleSheet("border-width: 2px;\n"
"background-color: rgba(118, 118, 118, 0);\n"
"border-style: solid;\n"
"border-color: rgb(118, 118, 118);\n"
"")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 3, 7, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem23, 3, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.verticalGroupBox_2)
        self.label_17.setStyleSheet("border-width: 2px;\n"
"background-color: rgba(118, 118, 118, 0);\n"
"border-style: solid;\n"
"border-color: rgb(118, 118, 118);\n"
"")
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 7, 3, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem24, 2, 1, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem25, 7, 8, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.verticalGroupBox_2)
        self.label_10.setStyleSheet("border-width: 2px;\n"
"background-color: rgba(118, 118, 118, 0);\n"
"border-style: solid;\n"
"border-color: rgb(118, 118, 118);\n"
"")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 9, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem26, 3, 10, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem27, 1, 10, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.verticalGroupBox_2)
        self.label_6.setMinimumSize(QtCore.QSize(91, 140))
        self.label_6.setStyleSheet("border-width: 2px;\n"
"background-color: rgba(118, 118, 118, 0);\n"
"border-style: solid;\n"
"border-color: rgb(118, 118, 118);\n"
"")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 1, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem28, 7, 10, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem29, 7, 4, 1, 1)
        spacerItem30 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem30, 2, 0, 1, 1)
        spacerItem31 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem31, 0, 0, 1, 1)
        spacerItem32 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem32, 4, 0, 1, 1)
        spacerItem33 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem33, 6, 0, 1, 1)
        spacerItem34 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem34, 8, 0, 1, 1)
        self.verticalLayout_18.addLayout(self.gridLayout)
        self.verticalLayout_3.addWidget(self.verticalGroupBox_2)
        self.horizontalLayout_11.addWidget(self.verticalGroupBox_output)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.gridLayout_2.addWidget(self.verticalGroupBox_main, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_cancel.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "行人重识别检测系统"))
        self.label_item.setText(_translate("MainWindow", "      Pedestrian Re-Identification Detection System          "))
        self.label_load_query.setText(_translate("MainWindow", "               待检索图库"))
        self.label_load_ref.setText(_translate("MainWindow", "                样本图库"))
        self.label_load_open.setText(_translate("MainWindow", "                打开图片"))
        self.label_load_assessment.setText(_translate("MainWindow", "               结果统计"))
        self.pushButton_start.setText(_translate("MainWindow", "开始检测"))
        self.pushButton_cancel.setText(_translate("MainWindow", "退出"))
