# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1156, 736)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_main = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_main.setAutoFillBackground(False)
        self.groupBox_main.setStyleSheet("background-image: url(:/img/ui/assert/215.jpg);")
        self.groupBox_main.setTitle("")
        self.groupBox_main.setObjectName("groupBox_main")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox_main)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 50, 1151, 681))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_main = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_main.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_main.setSpacing(0)
        self.horizontalLayout_main.setObjectName("horizontalLayout_main")
        self.groupBox_middle = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox_middle.setTitle("")
        self.groupBox_middle.setObjectName("groupBox_middle")
        self.groupBox_left = QtWidgets.QGroupBox(self.groupBox_middle)
        self.groupBox_left.setGeometry(QtCore.QRect(0, 0, 331, 681))
        self.groupBox_left.setTitle("")
        self.groupBox_left.setObjectName("groupBox_left")
        self.fileButton_ref = QtWidgets.QPushButton(self.groupBox_left)
        self.fileButton_ref.setGeometry(QtCore.QRect(10, 150, 61, 28))
        self.fileButton_ref.setMinimumSize(QtCore.QSize(55, 28))
        self.fileButton_ref.setMaximumSize(QtCore.QSize(16777215, 28))
        self.fileButton_ref.setStyleSheet("QPushButton{font-family: \"Microsoft YaHei\";\n"
"background-color: rgb(118, 118, 118);\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"color:white;\n"
"text-align: center center;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"padding-top: 4px;\n"
"padding-bottom: 4px;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-color: rgba(255, 255, 255, 255);\n"
"border-radius: 3px;}\n"
"\n"
"QPushButton:focus{outline: none;}\n"
"\n"
"QPushButton::pressed{font-family: \"Microsoft YaHei\";\n"
"                     font-size: 14px;\n"
"                     font-weight: bold;\n"
"                     color:rgb(200,200,200);\n"
"                     text-align: center center;\n"
"                     padding-left: 5px;\n"
"                     padding-right: 5px;\n"
"                     padding-top: 4px;\n"
"                     padding-bottom: 4px;\n"
"                     border-style: solid;\n"
"                     border-width: 0px;\n"
"                     border-color: rgba(255, 255, 255, 255);\n"
"                     border-radius: 3px;\n"
"                     background-color:  #bf513b;}\n"
"\n"
"QPushButton::disabled{font-family: \"Microsoft YaHei\";\n"
"                     font-size: 14px;\n"
"                     font-weight: bold;\n"
"                     color:rgb(200,200,200);\n"
"                     text-align: center center;\n"
"                     padding-left: 5px;\n"
"                     padding-right: 5px;\n"
"                     padding-top: 4px;\n"
"                     padding-bottom: 4px;\n"
"                     border-style: solid;\n"
"                     border-width: 0px;\n"
"                     border-color: rgba(255, 255, 255, 255);\n"
"                     border-radius: 3px;\n"
"                     background-color:  #bf513b;}\n"
"QPushButton::hover {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(48,148,243,80);}")
        self.fileButton_ref.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/assert/file_open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileButton_ref.setIcon(icon)
        self.fileButton_ref.setObjectName("fileButton_ref")
        self.fileButton_open = QtWidgets.QPushButton(self.groupBox_left)
        self.fileButton_open.setGeometry(QtCore.QRect(10, 230, 61, 28))
        self.fileButton_open.setMinimumSize(QtCore.QSize(55, 28))
        self.fileButton_open.setMaximumSize(QtCore.QSize(16777215, 28))
        self.fileButton_open.setStyleSheet("QPushButton{font-family: \"Microsoft YaHei\";\n"
"\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"color:white;\n"
"text-align: center center;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"padding-top: 4px;\n"
"padding-bottom: 4px;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-color: rgba(255, 255, 255, 255);\n"
"border-radius: 3px;\n"
"background-color: rgb(118, 118, 118);}\n"
"\n"
"QPushButton:focus{outline: none;}\n"
"\n"
"QPushButton::pressed{font-family: \"Microsoft YaHei\";\n"
"                     font-size: 14px;\n"
"                     font-weight: bold;\n"
"                     color:rgb(200,200,200);\n"
"                     text-align: center center;\n"
"                     padding-left: 5px;\n"
"                     padding-right: 5px;\n"
"                     padding-top: 4px;\n"
"                     padding-bottom: 4px;\n"
"                     border-style: solid;\n"
"                     border-width: 0px;\n"
"                     border-color: rgba(255, 255, 255, 255);\n"
"                     border-radius: 3px;\n"
"                     background-color:  #bf513b;}\n"
"\n"
"QPushButton::disabled{font-family: \"Microsoft YaHei\";\n"
"                     font-size: 14px;\n"
"                     font-weight: bold;\n"
"                     color:rgb(200,200,200);\n"
"                     text-align: center center;\n"
"                     padding-left: 5px;\n"
"                     padding-right: 5px;\n"
"                     padding-top: 4px;\n"
"                     padding-bottom: 4px;\n"
"                     border-style: solid;\n"
"                     border-width: 0px;\n"
"                     border-color: rgba(255, 255, 255, 255);\n"
"                     border-radius: 3px;\n"
"                     background-color:  #bf513b;}\n"
"QPushButton::hover {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(48,148,243,80);}")
        self.fileButton_open.setText("")
        self.fileButton_open.setIcon(icon)
        self.fileButton_open.setObjectName("fileButton_open")
        self.label_text_query = QtWidgets.QLabel(self.groupBox_left)
        self.label_text_query.setGeometry(QtCore.QRect(130, 30, 171, 40))
        self.label_text_query.setMinimumSize(QtCore.QSize(0, 0))
        self.label_text_query.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_text_query.setStyleSheet("\n"
"    font: 11pt \"华文楷体\";\n"
"    font-size: 22px;\n"
"    font-weight: bold;\n"
"         border-radius:9px;\n"
"        background:rgba(66, 195, 255, 0);\n"
"    color: rgba(170, 255, 255,200);\n"
"\n"
"\n"
"")
        self.label_text_query.setObjectName("label_text_query")
        self.lineEdit_query = QtWidgets.QLineEdit(self.groupBox_left)
        self.lineEdit_query.setGeometry(QtCore.QRect(80, 70, 241, 31))
        self.lineEdit_query.setStyleSheet("")
        self.lineEdit_query.setObjectName("lineEdit_query")
        self.textEdit_result = QtWidgets.QTextEdit(self.groupBox_left)
        self.textEdit_result.setGeometry(QtCore.QRect(20, 520, 301, 128))
        self.textEdit_result.setMinimumSize(QtCore.QSize(64, 128))
        self.textEdit_result.setStyleSheet("border-width: 2px;\n"
"background-color: rgba(118, 118, 118, 0);\n"
"border-style: solid;\n"
"border-color: rgb(118, 118, 118);\n"
"")
        self.textEdit_result.setObjectName("textEdit_result")
        self.fileButton_query = QtWidgets.QPushButton(self.groupBox_left)
        self.fileButton_query.setGeometry(QtCore.QRect(10, 70, 61, 28))
        self.fileButton_query.setMinimumSize(QtCore.QSize(55, 28))
        self.fileButton_query.setMaximumSize(QtCore.QSize(16777215, 28))
        self.fileButton_query.setStyleSheet("QPushButton{font-family: \"Microsoft YaHei\";\n"
"\n"
"background-color: rgb(118, 118, 118);\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"color:white;\n"
"text-align: center center;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"padding-top: 4px;\n"
"padding-bottom: 4px;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-color: rgba(255, 255, 255, 255);\n"
"border-radius: 3px;}\n"
"\n"
"QPushButton:focus{outline: none;}\n"
"\n"
"QPushButton::pressed{font-family: \"Microsoft YaHei\";\n"
"                     font-size: 14px;\n"
"                     font-weight: bold;\n"
"                     color:rgb(200,200,200);\n"
"                     text-align: center center;\n"
"                     padding-left: 5px;\n"
"                     padding-right: 5px;\n"
"                     padding-top: 4px;\n"
"                     padding-bottom: 4px;\n"
"                     border-style: solid;\n"
"                     border-width: 0px;\n"
"                     border-color: rgba(255, 255, 255, 255);\n"
"                     border-radius: 3px;\n"
"                     background-color:  #bf513b;}\n"
"\n"
"QPushButton::disabled{font-family: \"Microsoft YaHei\";\n"
"                     font-size: 14px;\n"
"                     font-weight: bold;\n"
"                     color:rgb(200,200,200);\n"
"                     text-align: center center;\n"
"                     padding-left: 5px;\n"
"                     padding-right: 5px;\n"
"                     padding-top: 4px;\n"
"                     padding-bottom: 4px;\n"
"                     border-style: solid;\n"
"                     border-width: 0px;\n"
"                     border-color: rgba(255, 255, 255, 255);\n"
"                     border-radius: 3px;\n"
"                     background-color:  #bf513b;}\n"
"QPushButton::hover {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(48,148,243,80);}")
        self.fileButton_query.setText("")
        self.fileButton_query.setIcon(icon)
        self.fileButton_query.setObjectName("fileButton_query")
        self.lineEdit_open = QtWidgets.QLineEdit(self.groupBox_left)
        self.lineEdit_open.setGeometry(QtCore.QRect(80, 230, 241, 31))
        self.lineEdit_open.setStyleSheet("")
        self.lineEdit_open.setObjectName("lineEdit_open")
        self.label_text_open = QtWidgets.QLabel(self.groupBox_left)
        self.label_text_open.setGeometry(QtCore.QRect(150, 190, 151, 40))
        self.label_text_open.setMinimumSize(QtCore.QSize(0, 0))
        self.label_text_open.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_text_open.setStyleSheet("\n"
"    font: 11pt \"华文楷体\";\n"
"    font-size: 22px;\n"
"    font-weight: bold;\n"
"         border-radius:9px;\n"
"        background:rgba(66, 195, 255, 0);\n"
"    color: rgba(170, 255, 255,200);\n"
"")
        self.label_text_open.setObjectName("label_text_open")
        self.label_text_ref = QtWidgets.QLabel(self.groupBox_left)
        self.label_text_ref.setGeometry(QtCore.QRect(120, 110, 191, 40))
        self.label_text_ref.setMinimumSize(QtCore.QSize(0, 0))
        self.label_text_ref.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_text_ref.setStyleSheet("QLabel\n"
"{        \n"
"    font: 11pt \"华文楷体\";\n"
"    font-size: 22px;\n"
"    font-weight: bold;\n"
"         border-radius:9px;\n"
"        background:rgba(66, 195, 255, 0);\n"
"    color: rgba(170, 255, 255,200);\n"
"\n"
"}\n"
"")
        self.label_text_ref.setObjectName("label_text_ref")
        self.lineEdit_ref = QtWidgets.QLineEdit(self.groupBox_left)
        self.lineEdit_ref.setGeometry(QtCore.QRect(80, 150, 241, 31))
        self.lineEdit_ref.setStyleSheet("")
        self.lineEdit_ref.setObjectName("lineEdit_ref")
        self.label_query = QtWidgets.QLabel(self.groupBox_left)
        self.label_query.setGeometry(QtCore.QRect(120, 280, 131, 191))
        self.label_query.setStyleSheet("border-width: 2px;\n"
"background-color: rgba(118, 118, 118, 0);\n"
"border-style: solid;\n"
"border-color: rgb(118, 118, 118);\n"
"")
        self.label_query.setText("")
        self.label_query.setObjectName("label_query")
        self.label_setting = QtWidgets.QLabel(self.groupBox_left)
        self.label_setting.setGeometry(QtCore.QRect(10, 0, 61, 40))
        self.label_setting.setMinimumSize(QtCore.QSize(0, 0))
        self.label_setting.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_setting.setStyleSheet("    \n"
"    font: 11pt \"华文楷体\";\n"
"    font-size: 22px;\n"
"    font-weight: bold;\n"
"         border-radius:9px;\n"
"        background:rgba(66, 195, 255, 0);\n"
"    color: rgba(170, 255, 255,200);\n"
"")
        self.label_setting.setObjectName("label_setting")
        self.label_14 = QtWidgets.QLabel(self.groupBox_left)
        self.label_14.setGeometry(QtCore.QRect(10, 480, 111, 40))
        self.label_14.setMinimumSize(QtCore.QSize(0, 0))
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_14.setStyleSheet("        \n"
"    font: 11pt \"华文楷体\";\n"
"    font-size: 22px;\n"
"    font-weight: bold;\n"
"         border-radius:9px;\n"
"        background:rgba(66, 195, 255, 0);\n"
"    color: rgba(170, 255, 255,200);\n"
"\n"
"")
        self.label_14.setObjectName("label_14")
        self.groupBox_right = QtWidgets.QGroupBox(self.groupBox_middle)
        self.groupBox_right.setGeometry(QtCore.QRect(330, 0, 821, 681))
        self.groupBox_right.setTitle("")
        self.groupBox_right.setObjectName("groupBox_right")
        self.pushButton_start = QtWidgets.QPushButton(self.groupBox_right)
        self.pushButton_start.setGeometry(QtCore.QRect(30, 10, 111, 41))
        self.pushButton_start.setStyleSheet("QPushButton{font-family: \"Microsoft YaHei\";\n"
"background-color: rgb(118, 118, 118);\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"color:white;\n"
"text-align: center center;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"padding-top: 4px;\n"
"padding-bottom: 4px;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-color: rgba(255, 255, 255, 255);\n"
"border-radius: 3px;}\n"
"\n"
"QPushButton:focus{outline: none;}\n"
"\n"
"QPushButton::pressed{font-family: \"Microsoft YaHei\";\n"
"                     font-size: 14px;\n"
"                     font-weight: bold;\n"
"                     color:rgb(200,200,200);\n"
"                     text-align: center center;\n"
"                     padding-left: 5px;\n"
"                     padding-right: 5px;\n"
"                     padding-top: 4px;\n"
"                     padding-bottom: 4px;\n"
"                     border-style: solid;\n"
"                     border-width: 0px;\n"
"                     border-color: rgba(255, 255, 255, 255);\n"
"                     border-radius: 3px;\n"
"                     background-color:  #bf513b;}\n"
"\n"
"QPushButton::disabled{font-family: \"Microsoft YaHei\";\n"
"                     font-size: 14px;\n"
"                     font-weight: bold;\n"
"                     color:rgb(200,200,200);\n"
"                     text-align: center center;\n"
"                     padding-left: 5px;\n"
"                     padding-right: 5px;\n"
"                     padding-top: 4px;\n"
"                     padding-bottom: 4px;\n"
"                     border-style: solid;\n"
"                     border-width: 0px;\n"
"                     border-color: rgba(255, 255, 255, 255);\n"
"                     border-radius: 3px;\n"
"                     background-color:  #bf513b;}\n"
"QPushButton::hover {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(48,148,243,80);}")
        self.pushButton_start.setObjectName("pushButton_start")
        self.label_file_11 = QtWidgets.QLabel(self.groupBox_right)
        self.label_file_11.setGeometry(QtCore.QRect(90, 370, 91, 141))
        self.label_file_11.setStyleSheet("border-width: 2px;\n"
"background-color: rgba(118, 118, 118, 0);\n"
"border-style: solid;\n"
"border-color: rgb(118, 118, 118);\n"
"")
        self.label_file_11.setText("")
        self.label_file_11.setObjectName("label_file_11")
        self.label_file_19 = QtWidgets.QLabel(self.groupBox_right)
        self.label_file_19.setGeometry(QtCore.QRect(520, 520, 91, 141))
        self.label_file_19.setStyleSheet("border-width: 2px;\n"
"background-color: rgba(118, 118, 118, 0);\n"
"border-style: solid;\n"
"border-color: rgb(118, 118, 118);\n"
"")
        self.label_file_19.setText("")
        self.label_file_19.setObjectName("label_file_19")
        self.label_file_5 = QtWidgets.QLabel(self.groupBox_right)
        self.label_file_5.setGeometry(QtCore.QRect(660, 70, 91, 141))
        self.label_file_5.setStyleSheet("border-width: 2px;\n"
"background-color: rgba(118, 118, 118, 0);\n"
"border-style: solid;\n"
"border-color: rgb(118, 118, 118);\n"
"")
        self.label_file_5.setText("")
        self.label_file_5.setObjectName("label_file_5")
        self.label_file_7 = QtWidgets.QLabel(self.groupBox_right)
        self.label_file_7.setGeometry(QtCore.QRect(230, 220, 91, 141))
        self.label_file_7.setStyleSheet("border-width: 2px;\n"
"background-color: rgba(118, 118, 118, 0);\n"
"border-style: solid;\n"
"border-color: rgb(118, 118, 118);\n"
"")
        self.label_file_7.setText("")
        self.label_file_7.setObjectName("label_file_7")
        self.label_file_18 = QtWidgets.QLabel(self.groupBox_right)
        self.label_file_18.setGeometry(QtCore.QRect(380, 520, 91, 141))
        self.label_file_18.setStyleSheet("border-width: 2px;\n"
"background-color: rgba(118, 118, 118, 0);\n"
"border-style: solid;\n"
"border-color: rgb(118, 118, 118);\n"
"")
        self.label_file_18.setText("")
        self.label_file_18.setObjectName("label_file_18")
        self.label_file_6 = QtWidgets.QLabel(self.groupBox_right)
        self.label_file_6.setGeometry(QtCore.QRect(90, 220, 91, 141))
        self.label_file_6.setStyleSheet("border-width: 2px;\n"
"background-color: rgba(118, 118, 118, 0);\n"
"border-style: solid;\n"
"border-color: rgb(118, 118, 118);\n"
"")
        self.label_file_6.setText("")
        self.label_file_6.setObjectName("label_file_6")
        self.label_file_1 = QtWidgets.QLabel(self.groupBox_right)
        self.label_file_1.setGeometry(QtCore.QRect(90, 70, 91, 141))
        self.label_file_1.setStyleSheet("border-width: 2px;\n"
"background-color: rgba(118, 118, 118, 0);\n"
"border-style: solid;\n"
"border-color: rgb(118, 118, 118);\n"
"")
        self.label_file_1.setLineWidth(1)
        self.label_file_1.setText("")
        self.label_file_1.setObjectName("label_file_1")
        self.label_file_3 = QtWidgets.QLabel(self.groupBox_right)
        self.label_file_3.setGeometry(QtCore.QRect(380, 70, 91, 141))
        self.label_file_3.setStyleSheet("border-width: 2px;\n"
"background-color: rgba(118, 118, 118, 0);\n"
"border-style: solid;\n"
"border-color: rgb(118, 118, 118);\n"
"")
        self.label_file_3.setText("")
        self.label_file_3.setObjectName("label_file_3")
        self.label_file_14 = QtWidgets.QLabel(self.groupBox_right)
        self.label_file_14.setGeometry(QtCore.QRect(520, 370, 91, 141))
        self.label_file_14.setStyleSheet("border-width: 2px;\n"
"background-color: rgba(118, 118, 118, 0);\n"
"border-style: solid;\n"
"border-color: rgb(118, 118, 118);\n"
"")
        self.label_file_14.setText("")
        self.label_file_14.setObjectName("label_file_14")
        self.label_file_17 = QtWidgets.QLabel(self.groupBox_right)
        self.label_file_17.setGeometry(QtCore.QRect(230, 520, 91, 141))
        self.label_file_17.setStyleSheet("border-width: 2px;\n"
"background-color: rgba(118, 118, 118, 0);\n"
"border-style: solid;\n"
"border-color: rgb(118, 118, 118);\n"
"")
        self.label_file_17.setText("")
        self.label_file_17.setObjectName("label_file_17")
        self.label_file_12 = QtWidgets.QLabel(self.groupBox_right)
        self.label_file_12.setGeometry(QtCore.QRect(230, 370, 91, 141))
        self.label_file_12.setStyleSheet("border-width: 2px;\n"
"background-color: rgba(118, 118, 118, 0);\n"
"border-style: solid;\n"
"border-color: rgb(118, 118, 118);\n"
"")
        self.label_file_12.setText("")
        self.label_file_12.setObjectName("label_file_12")
        self.label_file_16 = QtWidgets.QLabel(self.groupBox_right)
        self.label_file_16.setGeometry(QtCore.QRect(90, 520, 91, 141))
        self.label_file_16.setStyleSheet("border-width: 2px;\n"
"background-color: rgba(118, 118, 118, 0);\n"
"border-style: solid;\n"
"border-color: rgb(118, 118, 118);\n"
"")
        self.label_file_16.setText("")
        self.label_file_16.setObjectName("label_file_16")
        self.label_file_8 = QtWidgets.QLabel(self.groupBox_right)
        self.label_file_8.setGeometry(QtCore.QRect(380, 220, 91, 141))
        self.label_file_8.setStyleSheet("border-width: 2px;\n"
"background-color: rgba(118, 118, 118, 0);\n"
"border-style: solid;\n"
"border-color: rgb(118, 118, 118);\n"
"")
        self.label_file_8.setText("")
        self.label_file_8.setObjectName("label_file_8")
        self.label_file_9 = QtWidgets.QLabel(self.groupBox_right)
        self.label_file_9.setGeometry(QtCore.QRect(520, 220, 91, 141))
        self.label_file_9.setStyleSheet("border-width: 2px;\n"
"background-color: rgba(118, 118, 118, 0);\n"
"border-style: solid;\n"
"border-color: rgb(118, 118, 118);\n"
"")
        self.label_file_9.setText("")
        self.label_file_9.setObjectName("label_file_9")
        self.label_file_20 = QtWidgets.QLabel(self.groupBox_right)
        self.label_file_20.setGeometry(QtCore.QRect(660, 520, 91, 141))
        self.label_file_20.setStyleSheet("border-width: 2px;\n"
"background-color: rgba(118, 118, 118, 0);\n"
"border-style: solid;\n"
"border-color: rgb(118, 118, 118);\n"
"")
        self.label_file_20.setText("")
        self.label_file_20.setObjectName("label_file_20")
        self.label_file_2 = QtWidgets.QLabel(self.groupBox_right)
        self.label_file_2.setGeometry(QtCore.QRect(230, 70, 91, 141))
        self.label_file_2.setStyleSheet("border-width: 2px;\n"
"background-color: rgba(118, 118, 118, 0);\n"
"border-style: solid;\n"
"border-color: rgb(118, 118, 118);\n"
"")
        self.label_file_2.setText("")
        self.label_file_2.setObjectName("label_file_2")
        self.label_file_4 = QtWidgets.QLabel(self.groupBox_right)
        self.label_file_4.setGeometry(QtCore.QRect(520, 70, 91, 141))
        self.label_file_4.setStyleSheet("border-width: 2px;\n"
"background-color: rgba(118, 118, 118, 0);\n"
"border-style: solid;\n"
"border-color: rgb(118, 118, 118);\n"
"")
        self.label_file_4.setText("")
        self.label_file_4.setObjectName("label_file_4")
        self.label_file_15 = QtWidgets.QLabel(self.groupBox_right)
        self.label_file_15.setGeometry(QtCore.QRect(660, 370, 91, 141))
        self.label_file_15.setStyleSheet("border-width: 2px;\n"
"background-color: rgba(118, 118, 118, 0);\n"
"border-style: solid;\n"
"border-color: rgb(118, 118, 118);\n"
"")
        self.label_file_15.setText("")
        self.label_file_15.setObjectName("label_file_15")
        self.label_file_10 = QtWidgets.QLabel(self.groupBox_right)
        self.label_file_10.setGeometry(QtCore.QRect(660, 220, 91, 141))
        self.label_file_10.setStyleSheet("border-width: 2px;\n"
"background-color: rgba(118, 118, 118, 0);\n"
"border-style: solid;\n"
"border-color: rgb(118, 118, 118);\n"
"")
        self.label_file_10.setText("")
        self.label_file_10.setObjectName("label_file_10")
        self.label_file_13 = QtWidgets.QLabel(self.groupBox_right)
        self.label_file_13.setGeometry(QtCore.QRect(380, 370, 91, 141))
        self.label_file_13.setStyleSheet("border-width: 2px;\n"
"background-color: rgba(118, 118, 118, 0);\n"
"border-style: solid;\n"
"border-color: rgb(118, 118, 118);\n"
"")
        self.label_file_13.setText("")
        self.label_file_13.setObjectName("label_file_13")
        self.horizontalLayout_main.addWidget(self.groupBox_middle)
        self.horizontalGroupBox_2 = QtWidgets.QGroupBox(self.groupBox_main)
        self.horizontalGroupBox_2.setGeometry(QtCore.QRect(10, 0, 1130, 51))
        self.horizontalGroupBox_2.setObjectName("horizontalGroupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalGroupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_item = QtWidgets.QLabel(self.horizontalGroupBox_2)
        self.label_item.setMinimumSize(QtCore.QSize(45, 45))
        self.label_item.setStyleSheet("image: url(:/img/ui/assert/icon.jpg);")
        self.label_item.setText("")
        self.label_item.setObjectName("label_item")
        self.horizontalLayout.addWidget(self.label_item)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.horizontalGroupBox_2)
        self.label_2.setMinimumSize(QtCore.QSize(150, 47))
        self.label_2.setStyleSheet("    font: 11pt \"华文楷体\";\n"
"    font-size: 25px;\n"
"    font-weight: bold;\n"
"         border-radius:9px;\n"
"        background:rgba(66, 195, 255, 0);\n"
"    color: rgba(170, 255, 255,200);\n"
"\n"
"")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_start_2 = QtWidgets.QPushButton(self.horizontalGroupBox_2)
        self.pushButton_start_2.setStyleSheet("QPushButton{font-family: \"Microsoft YaHei\";\n"
"background-color: rgb(118, 118, 118);\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"color:white;\n"
"text-align: center center;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"padding-top: 4px;\n"
"padding-bottom: 4px;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-color: rgba(255, 255, 255, 255);\n"
"border-radius: 3px;}\n"
"\n"
"QPushButton:focus{outline: none;}\n"
"\n"
"QPushButton::pressed{font-family: \"Microsoft YaHei\";\n"
"                     font-size: 14px;\n"
"                     font-weight: bold;\n"
"                     color:rgb(200,200,200);\n"
"                     text-align: center center;\n"
"                     padding-left: 5px;\n"
"                     padding-right: 5px;\n"
"                     padding-top: 4px;\n"
"                     padding-bottom: 4px;\n"
"                     border-style: solid;\n"
"                     border-width: 0px;\n"
"                     border-color: rgba(255, 255, 255, 255);\n"
"                     border-radius: 3px;\n"
"                     background-color:  #bf513b;}\n"
"\n"
"QPushButton::disabled{font-family: \"Microsoft YaHei\";\n"
"                     font-size: 14px;\n"
"                     font-weight: bold;\n"
"                     color:rgb(200,200,200);\n"
"                     text-align: center center;\n"
"                     padding-left: 5px;\n"
"                     padding-right: 5px;\n"
"                     padding-top: 4px;\n"
"                     padding-bottom: 4px;\n"
"                     border-style: solid;\n"
"                     border-width: 0px;\n"
"                     border-color: rgba(255, 255, 255, 255);\n"
"                     border-radius: 3px;\n"
"                     background-color:  #bf513b;}\n"
"QPushButton::hover {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(48,148,243,80);}")
        self.pushButton_start_2.setObjectName("pushButton_start_2")
        self.horizontalLayout.addWidget(self.pushButton_start_2)
        self.verticalLayout.addWidget(self.groupBox_main)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_start_2.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.fileButton_ref.setToolTip(_translate("MainWindow", "文件"))
        self.fileButton_open.setToolTip(_translate("MainWindow", "文件"))
        self.label_text_query.setText(_translate("MainWindow", "Query图库"))
        self.fileButton_query.setToolTip(_translate("MainWindow", "文件"))
        self.label_text_open.setText(_translate("MainWindow", "打开图片"))
        self.label_text_ref.setText(_translate("MainWindow", "Reference图库"))
        self.label_setting.setText(_translate("MainWindow", "设置"))
        self.label_14.setText(_translate("MainWindow", "评价指标"))
        self.pushButton_start.setText(_translate("MainWindow", "开始检测"))
        self.label_2.setText(_translate("MainWindow", "行人重识别系统"))
        self.pushButton_start_2.setText(_translate("MainWindow", "退出"))
